/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BanDAO;
import Controller.MenuDAO;
import Model.Ban;
import Model.Menu;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanda
 */
public class QLHang extends javax.swing.JPanel {

    ArrayList<Menu> list = new ArrayList<>();
    ArrayList<Ban> listBan = new ArrayList<>();
    DefaultTableModel mTable;
    DefaultListModel<String> mList = new DefaultListModel<>();
    boolean them = false;

    /**
     * Creates new form QLHang
     */
    public QLHang() {
        initComponents();
        String[] heard = {"Mã menu", "Tên món", "Giá", "Loại", "Tình trạng"};
        mTable = new DefaultTableModel(null, heard) {
            @Override
            public boolean isCellEditable(int i, int i1) {
                return false;
            }
        };
        tab_menu.setModel(mTable);
        loadTable();
        lis_ban.setModel(mList);
        loadBan();
    }

    void loadBan() {
        mList.clear();
        listBan.clear();
        BanDAO.selectAll(listBan);
        for (Ban ban : listBan) {
            String s = ban.getMAB() + "          " + ban.getTenBan();
            mList.addElement(s);
        }
    }

    void loadTable() {
        while (mTable.getRowCount() > 0) {
            mTable.removeRow(0);
        }
        list.clear();
        MenuDAO.selectAll(list);
        for (Menu menu : list) {
            Vector v = new Vector();
            v.add(menu.getMAMN());
            v.add(menu.getTenMon());
            v.add(menu.getGia());
            v.add(menu.getLoai());
            v.add(menu.getTinhtrang().equals("1") ? "Còn" : "Hết");
            mTable.addRow(v);
        }
    }

    void cleanText() {
        txt_ma.setText("");
        txt_ten.setText("");
        txt_gia.setText("");
        cbb_loai.setSelectedIndex(0);
        rad_het.setSelected(true);
    }

    String chuyenMa(int i) {
        if (i < 10) {
            return "MN00" + i;
        }
        if (i < 100) {
            return "MN0" + i;
        } else {
            return "MN" + i;
        }
    }

    String chuyenMaBan(int i) {
        if (i < 10) {
            return "B00" + i;
        }
        if (i < 100) {
            return "B0" + i;
        } else {
            return "B" + i;
        }
    }

    void offThem(boolean b) {
        but_xoaMenu.setEnabled(b);
        but_suaMenu.setEnabled(b);
        tab_menu.setEnabled(b);
        but_huyMenu.setEnabled(!b);
        them = !b;
    }

    int intTinhTrang() {
        if (rad_con.isSelected()) {
            return 1;
        } else {
            return 0;
        }
    }

    Menu createMenu() {
        Menu menu = new Menu(txt_ma.getText(), txt_ten.getText(), Double.valueOf(txt_gia.getText()), cbb_loai.getSelectedItem().toString(), intTinhTrang() + "");
        return menu;
    }

    Ban createBan() {
        int index = 1;
        for (int i = 0; i < listBan.size(); i++) {
            if (!listBan.get(i).getMAB().equals(chuyenMaBan(index))) {
                break;
            }
            index++;
        }
        Ban ban = new Ban(chuyenMaBan(index), "Bàn " + index, "1");
        return ban;
    }

    int chuyenSo(String ma) {
        int n = Integer.valueOf(ma.substring(2));
        return n;
    }

    void mess(String s) {
        JOptionPane.showMessageDialog(this, s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgr_1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_menu = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lis_ban = new javax.swing.JList<>();
        but_themBan = new javax.swing.JButton();
        but_xoaBan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        txt_gia = new javax.swing.JTextField();
        cbb_loai = new javax.swing.JComboBox<>();
        but_themMenu = new javax.swing.JButton();
        but_huyMenu = new javax.swing.JButton();
        but_suaMenu = new javax.swing.JButton();
        but_xoaMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rad_con = new javax.swing.JRadioButton();
        rad_het = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(1200, 600));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 600));

        tab_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_menuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_menu);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Bàn ăn"));

        jScrollPane2.setViewportView(lis_ban);

        but_themBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Add.png"))); // NOI18N
        but_themBan.setText("Thêm");
        but_themBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_themBanActionPerformed(evt);
            }
        });

        but_xoaBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Trash.png"))); // NOI18N
        but_xoaBan.setText("Xóa");
        but_xoaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xoaBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_themBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_xoaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(but_themBan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but_xoaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thực đơn"));

        jLabel1.setText("Mã :");

        jLabel2.setText("Tên món:");

        jLabel3.setText("Giá:");

        jLabel4.setText("Loại:");

        txt_ma.setEditable(false);

        cbb_loai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Món chính", "Món thêm", "Đồ uống" }));

        but_themMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Add.png"))); // NOI18N
        but_themMenu.setText("Thêm");
        but_themMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_themMenuActionPerformed(evt);
            }
        });

        but_huyMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Delete.png"))); // NOI18N
        but_huyMenu.setText("Hủy");
        but_huyMenu.setEnabled(false);
        but_huyMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_huyMenuActionPerformed(evt);
            }
        });

        but_suaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Refresh.png"))); // NOI18N
        but_suaMenu.setText("Sửa");
        but_suaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_suaMenuActionPerformed(evt);
            }
        });

        but_xoaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Trash.png"))); // NOI18N
        but_xoaMenu.setText("Xóa");
        but_xoaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xoaMenuActionPerformed(evt);
            }
        });

        jLabel5.setText("Tình trạng:");

        rad_con.setBackground(new java.awt.Color(204, 255, 0));
        bgr_1.add(rad_con);
        rad_con.setSelected(true);
        rad_con.setText("Còn");

        rad_het.setBackground(new java.awt.Color(204, 255, 0));
        bgr_1.add(rad_het);
        rad_het.setText("Hết");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ten)
                            .addComponent(txt_gia)
                            .addComponent(cbb_loai, 0, 300, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rad_con)
                        .addGap(18, 18, 18)
                        .addComponent(rad_het)))
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(but_suaMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_huyMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_themMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_xoaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(161, 161, 161))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(but_themMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbb_loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rad_con)
                            .addComponent(rad_het)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(but_huyMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_suaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_xoaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    boolean kiemTra(){
        
        if(txt_gia.getText() == "") return false;
        try {
            double n = Double.valueOf(txt_gia.getText());
        } catch (Exception e) {
            return false;
        }
        if(txt_ma.getText() == "") return false;
        if(txt_ten.getText() == "") return false;
        return true;
    }
    
    private void tab_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_menuMouseClicked
        int row = tab_menu.getSelectedRow();
        if (row != -1) {
            txt_ma.setText(tab_menu.getValueAt(row, 0).toString());
            txt_ten.setText(tab_menu.getValueAt(row, 1).toString());
            txt_gia.setText(tab_menu.getValueAt(row, 2).toString());
            cbb_loai.setSelectedItem(tab_menu.getValueAt(row, 3).toString());
            if (tab_menu.getValueAt(row, 4).toString().equals("Còn")) {
                rad_con.setSelected(true);
            } else {
                rad_het.setSelected(true);
            }
        }
    }//GEN-LAST:event_tab_menuMouseClicked

    private void but_huyMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_huyMenuActionPerformed
        cleanText();
        offThem(true);
        them = false;
    }//GEN-LAST:event_but_huyMenuActionPerformed

    private void but_suaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_suaMenuActionPerformed
        if(!kiemTra()){
                JOptionPane.showMessageDialog(this, "Thông tin đã nhập không hợp lệ!!");
                return;
            }
        if (txt_ma.getText().isEmpty()) {
            return;
        }
        int canhBao = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhập không ?", "UPDATE", JOptionPane.OK_CANCEL_OPTION);
        if (canhBao != 0) {
            return;
        }
        int row = tab_menu.getSelectedRow();
        if (!txt_ma.getText().equals(tab_menu.getValueAt(row, 0))) {
            mess("Mã menu được chọn không khớp với mã menu text!!!");
            return;
        }
        Menu menu = createMenu();
        if (MenuDAO.update(menu)) {
            mess("Cập nhập thành công!");
            loadTable();
        } else {
            mess("Cập nhập thất bại!");
        }
    }//GEN-LAST:event_but_suaMenuActionPerformed

    private void but_themMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_themMenuActionPerformed
        tab_menu.clearSelection();
        if (them) {
            if(!kiemTra()){
                JOptionPane.showMessageDialog(this, "Thông tin đã nhập không hợp lệ!!");
                return;
            }
            int canhBao = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không ?", "ADD", JOptionPane.OK_CANCEL_OPTION);
            if (canhBao != 0) {
                return;
            }
            Menu menu = createMenu();
            if (MenuDAO.insert(menu)) {
                mess("Thêm thành công!");
            } else {
                mess("Thêm thất bại!");
            }
            cleanText();
            offThem(true);
            loadTable();
        } else {
            cleanText();
            offThem(false);
            String ma = MenuDAO.selectMaMoiNhat();
            int max = chuyenSo(ma) + 1;
            txt_ma.setText(chuyenMa(max));
        }
    }//GEN-LAST:event_but_themMenuActionPerformed

    private void but_xoaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoaMenuActionPerformed

        int row = tab_menu.getSelectedRow();
        int canhBao = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ?", "DELETE", JOptionPane.OK_CANCEL_OPTION);
        if (canhBao != 0) {
            return;
        }
        if (!txt_ma.getText().equals(tab_menu.getValueAt(row, 0))) {
            mess("Mã menu được chọn không khớp với mã menu text!!!");
            return;
        }
        if (MenuDAO.delete(txt_ma.getText())) {
            mess("Xóa thành công!");
            loadTable();
            cleanText();
        } else {
            mess("Xóa thất bại!");
        }
    }//GEN-LAST:event_but_xoaMenuActionPerformed

    private void but_themBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_themBanActionPerformed
        int canhBao = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không ?", "ADD", JOptionPane.OK_CANCEL_OPTION);
        if (canhBao != 0) {
            return;
        }
        Ban ban = createBan();
        if (BanDAO.insert(ban)) {
            mess(ban.getTenBan() + " đã được thêm!");
            loadBan();
        } else {
            mess("Thêm không thành công");
        }
    }//GEN-LAST:event_but_themBanActionPerformed

    private void but_xoaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoaBanActionPerformed
        int row = lis_ban.getSelectedIndex();
        int canhBao = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ?", "Delete", JOptionPane.OK_CANCEL_OPTION);
        if (canhBao != 0) {
            return;
        }
        if (BanDAO.delete(listBan.get(row).getMAB())) {
            mess(listBan.get(row).getTenBan() + " đã được xóa!");
            loadBan();
        } else {
            mess("xóa không thành công");
        }
    }//GEN-LAST:event_but_xoaBanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgr_1;
    private javax.swing.JButton but_huyMenu;
    private javax.swing.JButton but_suaMenu;
    private javax.swing.JButton but_themBan;
    private javax.swing.JButton but_themMenu;
    private javax.swing.JButton but_xoaBan;
    private javax.swing.JButton but_xoaMenu;
    private javax.swing.JComboBox<String> cbb_loai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lis_ban;
    private javax.swing.JRadioButton rad_con;
    private javax.swing.JRadioButton rad_het;
    private javax.swing.JTable tab_menu;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables
}
